server:
  protocol: http
  hostname: 192.168.50.128
  port: 4000
  
api:
  tmdb:
    apikey: 'c729bbc07bb8542dd22c1d740f0c5bf5'
    imgrul: 'http://image.tmdb.org/t/p/original'

database:
    client: postgresql
    connection:
        database: metadata-manager
        host: '192.168.50.251'
        port: 3001
        user: admin
        password: admin
    migrations:
        tableName: knex_migrations
        directory: ./src/models/migrations
    pool:
        min: 2
        max: 10