server:
    name: metadata-manager-server
    protocol: http
    hostname: 192.168.50.128
    port: 3000
directory:
    public: public
    image: image
tmdb:
    apiKey: 'c729bbc07bb8542dd22c1d740f0c5bf5'
    imageURL: 'http://image.tmdb.org/t/p/'
    sizes:
        backdrop:
            - "w300"
            - "w780"
            - "w1280"
            - "original"
        logo:
            - "w45"
            - "w92"
            - "w154"
            - "w185"
            - "w300"
            - "w500"
            - "original"
        poster:
            - "w92"
            - "w154"
            - "w185"
            - "w342"
            - "w500"
            - "w780"
            - "original"
        profile:
            - "w45"
            - "w185"
            - "h632"
            - "original"
        still:
            - "w92"
            - "w185"
            - "w300"
            - "original"
        all:
            - "w45"
            - "w92"
            - "w154"
            - "w185"
            - "w300"
            - "w342"
            - "w500"
            - "h632"
            - "w780"
            - "w1280"
            - "original"