database:
    client: postgresql
    connection:
        database: metadata-manager
        host: 192.168.50.166
        port: 3001
        user: admin
        password: admin
    migrations:
        tableName: knex_migrations
        directory: ./src/models/migrations
    pool:
        min: 2
        max: 10